version: "3"

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: project_backend
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - project-network

  mongodb:
    image: mongo
    container_name: project_mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - project-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: project_frontend
    volumes:
      - ./app/node_modules
      - ./client:/app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    networks:
      - project-network
  # nginx:
  #   restart: always
  #   depends_on:
  #     - client
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80
  #   networks:
  #     - project-network

networks:
  project-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
