version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
volumes:
  data:
  logs: