const messages = {
  tr: {
    detailsLabel: "Detay",
    allDayLabel: "Tüm Gün",
    titleLabel: "Başlık",
    commitCommand: "Kaydet",
    moreInformationLabel: "Daha Fazla Bilgi",
    repeatLabel: "Tekrar",
    notesLabel: "Notlar",
    never: "Asla",
    daily: "Günlük",
    weekly: "Haftalık",
    monthly: "Aylık",
    yearly: "Yıllık",
    repeatEveryLabel: "Her Birini Tekrarla",
    daysLabel: "Günler",
    endRepeatLabel: "Tekrarlamayı Sonlandır",
    onLabel: "Açık",
    afterLabel: "Sonra",
    occurrencesLabel: "Olaylar",
    weeksOnLabel: "Haftalar",
    monthsLabel: "Aylar",
    ofEveryMonthLabel: "Her ayın",
    theLabel: "Bu",
    firstLabel: "İlk",
    secondLabel: "İkinci",
    thirdLabel: "Üçüncü",
    fourthLabel: "Dördüncü",
    lastLabel: "Son",
    yearsLabel: "Yıllar",
    everyLabel: "Her",
    cancelButton: "Iptal",
    discardButton: "Sil",
    confirmCancelMessage: "Kaydedilmemiş değişiklikler silinsin mi?",
    confirmDeleteMessage: "Olay silinsin mi?",
    deleteButton: "Sil",
    menuEditingTitle: "Yinelenen olayı düzenle",
    current: "Bu randevu",
    currentAndFollowing: "Bu ve sonraki olaylar",
    all: "Tüm olaylar",
    menuDeletingTitle: "Yinelenen olayı sil",
    commitButton: "Kaydet",
  },
};

export default messages;
